append files from usb rather than copying over

diff --git a/scriptmodules/supplementary/usbromservice/01_retropie_copyroms b/scriptmodules/supplementary/usbromservice/01_retropie_copyroms
--- a/scriptmodules/supplementary/usbromservice/01_retropie_copyroms
+++ b/scriptmodules/supplementary/usbromservice/01_retropie_copyroms
@@ -19,6 +19,8 @@ usb_path="$UM_MOUNTPOINT/retropie"
 usb_path_from_rp="$usb_path/configs/from_retropie"
 usb_path_to_rp="$usb_path/configs/to_retropie"
 
+echo "usb_path"
+
 declare -A path_mapping
 
 # mapping from usb_path_to_rp/* to retropie location
@@ -63,23 +65,28 @@ for dir in roms BIOS; do
     chown -R $user:$user "$retropie_path/$dir"
 done
 
-log info "Syncing configs ..."
-# copy configs to usb
-for to in "${!path_mapping[@]}"; do
-    from=${path_mapping[$to]}
-    rsync -rtu --exclude '._*' --max-delete=-1 "$from/" "$usb_path_from_rp/$to/" >/dev/null 2>&1 || log err "rsync failed to sync $from/ -> $usb_path_from_rp/$to/, returned error code $?"
-done
+# add system link from usb mount to original roms directory
+log info "adding system between $usb_path and $retropie_path"
+cp -ans $usb_path $retropie_path
+log info "added yay!"
 
-# copy configs from usb
-for from in $(find "$usb_path_to_rp/" -mindepth 1 -maxdepth 1); do
-    # basename
-    from_bn=${from##*/}
-    to=${path_mapping[$from_bn]}
-    if [[ -n "$to" ]]; then
-        rsync -rtu --exclude '._*' --max-delete=-1 "$from/" "$to/" >/dev/null 2>&1 || log err "rsync failed to sync $from/ -> $to/ configuration, returned error code $?"
-        chown -R $user:$user "$to"
-    fi
-done
+# log info "Syncing configs ..."
+# # copy configs to usb
+# for to in "${!path_mapping[@]}"; do
+#     from=${path_mapping[$to]}
+#     rsync -rtu --exclude '._*' --max-delete=-1 "$from/" "$usb_path_from_rp/$to/" >/dev/null 2>&1 || log err "rsync failed to sync $from/ -> $usb_path_from_rp/$to/, returned error code $?"
+# done
 
-# unmount USB stick
-umount "$UM_MOUNTPOINT"
+# # copy configs from usb
+# for from in $(find "$usb_path_to_rp/" -mindepth 1 -maxdepth 1); do
+#     # basename
+#     from_bn=${from##*/}
+#     to=${path_mapping[$from_bn]}
+#     if [[ -n "$to" ]]; then
+#         rsync -rtu --exclude '._*' --max-delete=-1 "$from/" "$to/" >/dev/null 2>&1 || log err "rsync failed to sync $from/ -> $to/ configuration, returned error code $?"
+#         chown -R $user:$user "$to"
+#     fi
+# done
+
+# # unmount USB stick
+# umount "$UM_MOUNTPOINT"
